version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: gestur-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gestur_db
      POSTGRES_USER: gestur_user
      POSTGRES_PASSWORD: gestur_password
